name: Sync all organization members to all-members team

on:
  schedule:
    - cron: '0 3 * * *'   # runs every day at 03:00 UTC
  workflow_dispatch:       # allows manual trigger

jobs:
  sync-members:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh jq

      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.HOCHE_MP2I_SYNC }}" | gh auth login --with-token

      - name: Sync organization members to all-members team
        env:
          ORG: Hoche-MP2I-MPI          # 🔹 Change this
          TEAM_SLUG: MP2I      # 🔹 Change if your team slug differs
        run: |
          echo "Fetching members of $ORG..."
          gh api orgs/$ORG/members --paginate --jq '.[].login' | while read user; do
            echo "Adding $user to $TEAM_SLUG..."
            gh api \
              -X PUT \
              orgs/$ORG/teams/$TEAM_SLUG/memberships/$user \
              -f role=member \
              >/dev/null
          done

          echo "✅ Sync completed."
